### ISSUE TITLE
Slow GPU usage rate

### ISSUE THREAD

**Issue by zhexinli** [facebookresearch/deit#81]
Hello, thank you for your code. I'm training with deit_tiny, but the training is very slow and the gpu usage rate is very low as showed below.
![image](https://user-images.githubusercontent.com/44015820/112631226-90fed300-8e71-11eb-83a9-010ad5cb31da.png)
We use 32 cpu and 8 gpu, the total memory(RAM) is 200G. The training command line is
`python -m torch.distributed.launch \
--nproc_per_node=8 --use_env main.py \
--num_workers 32 \
--model deit_tiny_patch16_224 \
--batch-size 128 \
--repeated-aug \
--data-path /data/lizhexin/public-datasets-contrib/ILSVRC2012/original \
--output_dir ./result`
According to the usage graph, it doesn't look like the gpus are waiting for the data. Sometime the gpus even stopped for a long time.
I've trained for nearly a day and only got 37 epochs, much slow than 4 gpus finishing 75 epoches per day in your paper.
What could cause this problem? Thanks for your reply!

**Comment by TouvronHugo** [comment]
Hi @zhexinli ,
Thanks for your message,
`--num_workers`  It is to specify the number of cpu available per gpu, it should be 4 in your case that may be causing the problem but I am not sure.
Best,
Hugo

**Comment by zhexinli** [comment]
Thank you! I set the num_workers to be 4 and it worked now!
